service: k2-identifier

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-ifelse

custom:
  currentStage: ${opt:stage, self:provider.stage}
  serverlessIfElse:
    - If: '"${self:custom.currentStage}" == "local"'
      Set:
        functions.nextIdentifier.handler: ./handler.nextIdentifier

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

  ecr:
    images:
      k2_identifier:
        path: ./

  environment:
    PROVIDER_URL: ${file(./env/config.${opt:stage, 'dev'}.json):PROVIDER_URL}
    NONCE_MANAGER_ADDRESS: ${file(./env/config.${opt:stage, 'dev'}.json):NONCE_MANAGER_ADDRESS}

functions:
  nextIdentifier:
    image:
      name: k2_identifier
      command:
        - handler.nextIdentifier
      entryPoint:
        - '/lambda-entrypoint.sh'
    memorySize: 3500
    timeout: 30
    events:
      - http:
          path: nextIdentifier
          method: post
          cors: true
    vpc:
      securityGroupIds:
        - sg-ebdf849f
      subnetIds:
        - subnet-0070f2ed34a5f74a7

