service: k2-liveness

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-ifelse

custom:
  currentStage: ${opt:stage, self:provider.stage}
  serverlessIfElse:
    - If: '"${self:custom.currentStage}" == "local"'
      Set:
        functions.liveness.handler: ./handler.liveness

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

  ecr:
    images:
      k2_liveness:
        path: ./

functions:
  liveness:
    image:
      name: k2_liveness
      command:
        - handler.liveness
      entryPoint:
        - '/lambda-entrypoint.sh'
    memorySize: 3500
    timeout: 30
    events:
      - http:
          path: liveness
          method: get
          cors: true
    vpc:
      securityGroupIds:
        - sg-ebdf849f
      subnetIds:
        - subnet-0070f2ed34a5f74a7

